export const quotes = [
    "Time waits for no one.",
    "Moments are memories in the making.",
    "The best time to start was yesterday. The next best is now.",
    "Cherish each tick of the clock.",
    "Your time is your life.",
    "Time is the most valuable thing we have.",
    "Every moment is a fresh beginning.",
    "Time flies when you're having fun.",
    "Time is the thread of life.",
    "Seconds turn into stories.",
    "Don't count time, make time count.",
    "Tick tock, life moves on.",
    "Time is the silent teacher.",
    "The future depends on what you do now.",
    "Lost time is never found again.",
    "Punctuality is the thief of procrastination.",
    "Time is the canvas, actions are the paint.",
    "A minute saved is a moment earned.",
    "Yesterday is gone, tomorrow is uncertain—today is a gift.",
    "Time reveals all truths.",
    "Life is measured in moments, not minutes.",
    "The clock never stops, but you can start anytime.",
    "Waste time, and you waste life.",
    "Time is the one currency you can't earn back.",
    "Every second is a chance to change.",
    "The present is the only time you control.",
    "Time doesn't heal, but it teaches.",
    "Make time for what matters.",
    "A well-spent day brings happy sleep.",
    "The past is a lesson, not a home.",
    "Time is the fire in which we burn.",
    "Now is the only moment you own.",
    "An hour lost is a future delayed.",
    "Time is the wisest counselor.",
    "The clock is ticking—start living.",
    "Time is a river, not a reservoir.",
    "Moments pass, memories last.",
    "Time slips through careless hands.",
    "Tomorrow is a promise, not a plan.",
    "Count memories, not minutes.",
    "Time molds what patience builds.",
    "Let each second be a seed.",
    "Time tests all intentions.",
    "Don't chase time, walk with it.",
    "Moments fade, impacts remain.",
    "Time whispers what haste forgets.",
    "Life unfolds one tick at a time.",
    "Time waits for your courage.",
    "The clock moves, whether you do or not.",
    "Seconds lost are stories untold.",
    "Time's gift is perspective.",
    "Rush less, live more.",
    "Time dances to its own tune.",
    "Make memories, not excuses.",
    "Time enriches quiet hearts.",
    "Moments matter more than milestones.",
    "Don't borrow tomorrow's worries.",
    "Time tells what truth hides.",
    "Each sunrise resets the clock.",
    "Time polishes rough edges.",
    "Spend time like you spend money—wisely.",
    "One day you'll wish for today.",
    "Time's pace is yours to match.",
    "Pause often, time won't.",
    "Time builds what haste breaks.",
    "Clocks tick, hearts beat—both measure life.",
    "Time is the stage, you write the script.",
    "Late starts are better than never.",
    "Time unravels every secret.",
    "The moment you're in is all you own.",
    "Time flows; make sure you're swimming.",
    "Time's melody plays only once—listen closely.",
    "A second's decision can change a lifetime.",
    "The hourglass never pauses for regrets.",
    "Time is the architect of character.",
    "Moments are the brushstrokes of destiny.",
    "Watches measure time, but presence measures life.",
    "Time's river carries both the patient and rushed.",
    "The present is time's only guaranteed gift.",
    "Every ending is time's new beginning.",
    "Time heals wounds but scars remain as lessons.",
    "The clock's hands point forward for a reason.",
    "Time spent laughing is never wasted.",
    "Yesterday's lessons fuel tomorrow's victories.",
    "Time magnifies what we nurture.",
    "An idle moment is a stolen opportunity.",
    "Time's tapestry weaves choices into fate.",
    "The past is a museum, not a residence.",
    "Time's value is known only when it's gone.",
    "Morning dew fades as time teaches impermanence.",
    "Future memories are born in present moments.",
    "Time is the silent partner in all achievements.",
    "Hurry empties moments of their magic.",
    "The sundial measures light, not just hours.",
    "Time's echo carries further than we imagine.",
    "Patience is time's favorite currency.",
    "A watched clock slows for the impatient.",
    "Time's mirror reflects what we truly value.",
    "Sunrises are time's daily reset button.",
    "The hourglass reminds: what falls will rise again.",
    "Time is the gardener of all possibilities.",
    "Rushed decisions bloom into lasting consequences.",
    "Time's current favors those who paddle with purpose.",
    "The present moment is time's only true possession.",
    "Time's arithmetic: subtract distractions, add meaning.",
    "A lifetime is just minutes, wisely spent.",
    "Time's fingerprint is unique on every life.",
    "The pendulum swings but never repeats its arc.",
    "Time is the quiet editor of all stories.",
    "Moments are the seeds of legacy.",
    "Time's compass always points to now.",
    "The calendar pages turn whether we're ready or not.",
    "Time is the invisible thread connecting all lives.",
    "Procrastination is time's favorite disguise.",
    "Time's recipe: mix intention with action, serve warm.",
    "The clock's face smiles at those who use time well.",
    "Time's mosaic is made of a million nows.",
    "Future you will thank present you for starting today.",
    "Time's whisper becomes a roar when ignored.",
    "The hourglass never asks if you're ready.",
    "Time is the canvas, attention is the brush.",
    "Moments multiply when shared with meaning.",
    "Time's alchemy turns effort into achievement.",
    "The present is time's only delivery.",
    "Time's river carves canyons from consistent drops.",
    "Watches tell time, but consciousness tells meaning.",
    "Time is the silent shareholder in all endeavors."
];